# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

appname: "autohome"
layout: "main"
charset: "UTF-8"
session: "YAML"
template: "template_toolkit"
behind_proxy: 1
logger: "file"
log: "debug"
show_errors: 1
access_log: 1
warnings: 1

engines:
  template:
    template_toolkit:
      encoding:  'utf8'
      start_tag: '[%'
      end_tag:   '%]'
  session:
    YAML:
      session_dir: "/tmp/dancer-sessions"
      session_expires: time() + 300

plugins:
  Ajax:
    content_type: 'application/json'


# Custom variables
user1: "admin"
pass1: "admin"

user2: "user"
pass2: "user"





