# configuration file for production environment

log: "warning"
logger: "file"
warnings: 0
show_errors: 0
route_cache: 1


plugins:
  DBIC:
    default:
      dsn: dbi:mysql:autohome:proddb
      schema_class: autohome::Schema
      user: matt
      password: notusedyet
      options:
        RaiseError: 1
        PrintError: 1

