apiVersion: v1
kind: Service
metadata:
    name: mattqmperlautohome
spec:
    type: LoadBalancer
    ports:
    - port: 80 
      targetPort: 3001
    selector:
        app: mattqmperlautohome
